Repository Rhythm-cmd/Learn.github.io, pull requests merged in 2022-10, with the labels that each got.

#2 Update
  index.html
Labels: good first issue, HacktoberFest2022, HacktoberFest-accepted

#4 Update README.txt
  README.txt
Labels: documentation, good first issue, HacktoberFest2022, HacktoberFest-accepted

#5 Update README.txt
  README.txt
Labels: documentation, good first issue, HacktoberFest2022, HacktoberFest-accepted

#8 Update Assignment.html
  Assignment.html
Labels: enhancement, HacktoberFest2022, HacktoberFest-accepted

#9 Update and rename README.txt to README.md
  README.md
Labels: documentation, HacktoberFest2022, HacktoberFest-accepted

#12 fix: add Linked In URL
  index.html
Labels: good first issue, HacktoberFest2022, HacktoberFest-accepted

#13 Update README.md
  README.md
Labels: documentation, HacktoberFest2022, HacktoberFest-accepted

#16 Update README.md
  README.md
Labels: HacktoberFest2022, HacktoberFest-accepted

#15 Remove dribble icon
  index.html
Labels: HacktoberFest2022, HacktoberFest-accepted
